(script static void (carter_falcon_intro)
	(ai_vehicle_enter_immediate (performance_get_actor carter) (ai_vehicle_get_from_squad intro_falcon_01 0) "falcon_p_bench_wpn")
	(performance_play_line "load_into_falcon_01")
	(performance_play_line "sleep_until_custom_animation_in_falcon_seat")
	(performance_play_line "point_anim")
	(performance_play_line "block_until_all_done")
	(sleep_until (>= (device_get_position dm_falcon01_start) .80) 1)
	(performance_play_line "sleep_until_its_time_to_communicate")
	(performance_play_line "custom_anim")
	(sleep_until (>= (device_get_position dm_falcon01_start) .97) 1)
	(performance_play_line "sleep_until_its_time_to_unload")
	(vehicle_unload (ai_vehicle_get_from_squad intro_falcon_01 0) "falcon_p_bench_wpn")
	(performance_play_line "unload_from_falcon")
	(sleep_until (not (vehicle_test_seat (ai_vehicle_get_from_squad intro_falcon_01 0) "falcon_p_bench_wpn")) 1)
	(performance_play_line "sleep_until_seat_is_empty")
	(performance_play_line "land_anim")
	(performance_play_line "set_alert_stance")
	(performance_play_line "sleep")
	(performance_play_line "commands_anim")
	(sleep_until (not (vehicle_test_seat (ai_vehicle_get_from_squad intro_falcon_01 0) "falcon_p_l1")) 1)
	(performance_play_line "sleep_until_player_seat_is_empty")
	(performance_play_line "block_all")
)

(script static void (kat_falcon_intro)
	(ai_vehicle_enter_immediate (performance_get_actor kat) (ai_vehicle_get_from_squad intro_falcon_02 0) "falcon_p_bench_wpn")
	(performance_play_line "load_into_falcon_02")
	(sleep_until (>= (device_get_position dm_falcon02_start) .65) 1)
	(performance_play_line "sleep_until_its_time_to_communicate")
	(performance_play_line "communication_anim")
	(sleep_until (>= (device_get_position dm_falcon02_start) .86) 1)
	(performance_play_line "sleep_until_its_time_to_unload")
	(vehicle_unload (ai_vehicle_get_from_squad intro_falcon_02 0) "falcon_p_bench_wpn")
	(performance_play_line "unload_from_falcon")
	(sleep 30)
	(performance_play_line "sleep_until_time_to_land")
	(performance_play_line "land")
	(performance_play_line "sleep")
	(cs_lower_weapon (performance_get_actor kat) TRUE)
	(performance_play_line "lower_weapon")
	(performance_play_line "goto_and_align")
	(performance_play_line "anim")
	(performance_play_line "alert")
	(sleep_until (not (vehicle_test_seat (ai_vehicle_get_from_squad intro_falcon_01 0) "falcon_p_l1")) 1)
	(performance_play_line_by_id 12)
	(performance_play_line "block_all")
)

(script static void (emile_falcon_intro)
	(ai_vehicle_enter_immediate (performance_get_actor emile) (ai_vehicle_get_from_squad intro_falcon_02 0) "falcon_p_r1_wpn")
	(performance_play_line "load_into_falcon_02")
	(sleep_until (>= (device_get_position dm_falcon02_start) .8333333) 1)
	(performance_play_line "sleep_until_its_time_to_unload")
	(vehicle_unload (ai_vehicle_get_from_squad intro_falcon_02 0) "falcon_p_r1_wpn")
	(performance_play_line "unload_from_falcon")
	(sleep 33)
	(performance_play_line "sleep")
	(performance_play_line "land")
	(performance_play_line "goto_and_align")
	(performance_play_line "anim")
	(sleep_until (not (vehicle_test_seat (ai_vehicle_get_from_squad intro_falcon_01 0) "falcon_p_l1")) 1)
	(performance_play_line "sleep_until_player_exits")
	(performance_play_line "block_all")
)

(script static void (jun_falcon_intro)
	(ai_vehicle_enter_immediate (performance_get_actor jun) (ai_vehicle_get_from_squad intro_falcon_01 0) "falcon_p_r1_wpn")
	(performance_play_line "load_into_falcon_01")
	(sleep_until (>= (device_get_position dm_falcon01_start) .75) 1)
	(performance_play_line "sleep_until_its_time_to_communicate")
	(performance_play_line "communication_anim")
	(performance_play_line "block_all")
)

(script static void (jorge_falcon_intro)
	(ai_vehicle_enter_immediate (performance_get_actor jorge) (ai_vehicle_get_from_squad intro_falcon_02 0) "falcon_p_l1_wpn")
	(performance_play_line "load_into_falcon_01")
	(performance_play_line "block_all")
)

