(script static void (thes_emile_rockclimb)
	(branch
		(branch_spartan (performance_get_actor emile))
		(empty_branch)
	)
	(performance_play_line "branch")
	(branch
		(>= s_bowl_objcon 40)
		(empty_branch2)
	)
	(performance_play_line "progress_branch")
	(performance_play_line "aim_at_rock")
	(performance_play_line "move_by_point")
	(performance_play_line "move_to_point")
	(performance_play_line "anim_rock_climb")
	(performance_play_line "anim_rock_climb_idle")
	(performance_play_line "anim_rock_climb_exit")
	(sleep_until (>= s_bowl_objcon 22) 1)
	(performance_play_line "sleep_until")
	(performance_play_line "block_until_done")
)

(script static void (thes_spartan_beacon)
	(branch
		(branch_spartan (performance_get_actor kat))
		(empty_branch)
	)
	(performance_play_line "kat_branch")
	(branch
		(branch_spartan (performance_get_actor carter))
		(empty_branch2)
	)
	(performance_play_line "carter_branch")
	(branch
		(= b_post_kiva 1)
		(empty_branch3)
	)
	(performance_play_line "bit_branch")
	(performance_play_line "kat_get_to_point")
	(performance_play_line "kat_alert5")
	(performance_play_line "carter_get_to_point")
	(performance_play_line "carter_move_alert_5")
	(performance_play_line "sync_beacon")
	(set b_post_kiva 1)
	(performance_play_line "set_boolean")
)

(script static void (thes_jorge_beacon)
	(branch
		(branch_spartan (performance_get_actor jorge))
		(empty_branch)
	)
	(performance_play_line "branch")
	(branch
		(= b_post_kiva 1)
		(empty_branch2)
	)
	(performance_play_line "progress_branch")
	(performance_play_line "jorge_goto_center")
	(performance_play_line "jorge_face")
	(sleep_until (= b_post_kiva 1) 1)
	(performance_play_line "sleep")
)

(script static void (thes_emile_beacon)
	(branch
		(branch_spartan (performance_get_actor emile))
		(empty_branch)
	)
	(performance_play_line "branch")
	(branch
		(= b_post_kiva 1)
		(empty_branch2)
	)
	(performance_play_line "progress_branch")
	(performance_play_line "emile_goto_01")
	(performance_play_line "emile_goto_02")
	(performance_play_line "emile_look_01")
	(performance_play_line "emile_look_02")
	(performance_play_line "emile_look_03")
	(performance_play_line "emile_look_03b")
	(performance_play_line "emile_goto_03")
	(performance_play_line "emile_look_04")
	(performance_play_line "emile_look_05")
	(performance_play_line "emile_goto_04")
	(performance_play_line "emile_look_06")
)

(script static void (thes_witnesses)
	(performance_play_line "open_door")
	(performance_play_line "jorge_enter")
	(performance_play_line "male01_enter")
	(performance_play_line "male02_sleep1")
	(performance_play_line "male02_enter")
	(performance_play_line "jorge_dialogue")
	(performance_play_line "male01_dialogue")
	(performance_play_line "male01_idle2")
	(performance_play_line "male02_idle")
	(performance_play_line "male02_hands_down")
	(performance_play_line "mom_sleep")
	(performance_play_line "mom_enter")
	(performance_play_line "daughter_enter_anim")
	(performance_play_line "mother_anim_loop")
	(performance_play_line "daughter_anim_loop")
	(performance_play_line "jorge_exit")
	(performance_play_line "male01_goto")
	(performance_play_line "mom_exit")
	(performance_play_line "daughter_exit")
	(performance_play_line "male02_exit")
	(performance_play_line "male01_exit")
	(performance_play_line "block_until_done01")
)

(script static void (thes_pickup)
	(performance_play_line "anim_slumped_horn")
	(performance_play_line "carter_goto")
	(performance_play_line "wait")
)

