(script static void (th_marine_bunker_00)
	(performance_play_line "m1_goto_01")
	(performance_play_line "m2_goto_01")
	(performance_play_line "m1_animate_01")
	(performance_play_line "m2_animate_01")
	(performance_play_line "m2_animate_02")
	(performance_play_line "m2_animate_03")
	(performance_play_line "m1_goto_02")
	(performance_play_line "m2_goto_02")
	(performance_play_line "m1_animate_02")
	(performance_play_line "m2_animate_04")
	(performance_play_line "m2_animate_05")
)

