(script static void (performance_pull)
	(print "I love cookies")
	(performance_play_line "carter_move_to_point")
	(performance_play_line "jun_move_to_point")
	(performance_play_line "jun_turn")
	(performance_play_line "jun_walk_back")
	(performance_play_line "carter_move_to_point_2")
	(performance_play_line "carter_pull_lever")
	(performance_play_line "jun_cover_carter")
)
