(script static void (thes_trooper_goto_break_window)
	(performance_play_line "move_to_center")
	(performance_play_line "break_window_animation")
)

(script static void (thes_trooper_goto_kick_enemy_body)
	(performance_play_line "move_to_center")
	(performance_play_line "kick_enemy_animation")
)

(script static void (thes_trooper_goto_salute)
	(performance_play_line "move_to_center")
	(performance_play_line "salute_animation")
)

(script static void (thes_trooper_goto_survey_environment)
	(performance_play_line "move_to_center")
	(performance_play_line "survey_equip_animation")
)

(script static void (thes_spartan_goto_crouch_look_around)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "crouch_look_animation")
)

(script static void (thes_spartan_goto_inspect_ground)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "crouch_inspect_ground")
)

(script static void (thes_spartan_goto_inv_enemy_body)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "inv_enemy_body_anim")
)

(script static void (thes_spartan_goto_inv_friendly_body)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "inv_friendly_body_anim")
)

(script static void (thes_spartan_goto_inv_room)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "inv_room_animation")
)

(script static void (thes_spartan_goto_kick_door)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "kick_door_animation")
)

(script static void (thes_spartan_goto_look_around_3_points)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 5)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "aim_at_01")
	(performance_play_line "aim_at_02")
	(performance_play_line "aim_at_03")
)

(script static void (thes_spartan_goto_poke_kick_body)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "poke_kick_body_animation")
)

(script static void (thes_spartan_goto_rock_jump01)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "rock_jump_animation")
)

(script static void (thes_spartan_goto_rock_jump02)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "rock_jump02")
)

(script static void (thes_spartan_goto_rock_jump03)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "rock_jump_animation")
)

(script static void (thes_spartan_goto_rock_jump04)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "rock_jump_animation")
)

(script static void (thes_spartan_goto_shuffle_aim_around)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "move_to_center")
	(performance_play_line "shuffle_aim_animation")
)

(script static void (thes_spartan_immediate_360_look)
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(performance_play_line "360_look_animation")
)

(script static void (thes_spartan_immediate_inspect_ground)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "crouch_inspect_ground")
)

(script static void (thes_spartan_immediate_shuffle_aim_around)	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "shuffle_aim_animation")
)

(script static void (thes_spartan_immediate_signal_attack)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "signal_attack_animation")
)

(script static void (thes_spartan_immediate_signal_cease_fire)	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "signal_cease_animation")
)

(script static void (thes_spartan_immediate_signal_come)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "signal_come_animation")
)

(script static void (thes_spartan_immediate_signal_deploy)
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_deploy_animation")
)

(script static void (thes_spartan_immediate_signal_find_cover)	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_cover_animation")
)

(script static void (thes_spartan_immediate_signal_freeze)
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_freeze")
)

(script static void (thes_spartan_immediate_signal_hear)
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_hear")
)

(script static void (thes_spartan_immediate_signal_hold_stop)
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 5)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(performance_play_line "signal_hold_animation")
)

(script static void (thes_spartan_immediate_signal_hurry)
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_hurry_animation")
)

(script static void (thes_spartan_immediate_signal_move_up)
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_move_up_animation")
)

(script static void (thes_spartan_immediate_signal_positive)
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_positive_animation")
)

(script static void (thes_spartan_immediate_signal_rally)
	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_rally_animation")
)

(script static void (thes_spartan_immediate_signal_rally_wave)	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_rally_wave_animation")
)

(script static void (thes_spartan_immediate_signal_spread_out)	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_spread_animation")
)

(script static void (thes_spartan_immediate_signal_take_point)	(branch
		(> (object_get_recent_body_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty03)
	)
	(performance_play_line "branch_on_body_damage")
	(branch
		(> (object_get_recent_shield_damage (ai_get_object (performance_get_actor spartan))) 0)
		(f_branch_empty02)
	)
	(performance_play_line "branch_on_shield_damage")
	(branch
		(>= (ai_combat_status (performance_get_actor spartan)) 3)
		(f_branch_empty01)
	)
	(performance_play_line "branch_on_combat_status")
	(performance_play_line "signal_take_point)animation")
)

(script static void (thes_trooper_immediate_adjust_backpack)
	(performance_play_line "sleep")
	(performance_play_line "adjust_backpack")
)

(script static void (thes_trooper_immediate_brace)
	(performance_play_line "sleep_trooper01")
	(performance_play_line "sleep_trooper02")
	(performance_play_line "sleep_trooper03")
	(performance_play_line "sleep_trooper04")
	(performance_play_line "brace_trooper01")
	(performance_play_line "brace_trooper02")
	(performance_play_line "brace_trooper03")
	(performance_play_line "brace_trooper04")
)

(script static void (thes_trooper_immediate_cover_dust)
	(performance_play_line "sleep_trooper01")
	(performance_play_line "sleep_trooper02")
	(performance_play_line "sleep_trooper03")
	(performance_play_line "sleep_trooper04")
	(performance_play_line "face_point_trooper01")
	(performance_play_line "face_point_trooper02")
	(performance_play_line "face_point_trooper03")
	(performance_play_line "face_point_trooper04")
	(performance_play_line "cover_dust_trooper01")
	(performance_play_line "cover_dust_trooper02")
	(performance_play_line "cover_dust_trooper03")
	(performance_play_line "cover_dust_trooper04")
)

(script static void (thes_trooper_immediate_look_up_ship)
	(performance_play_line "sleep_trooper01")
	(performance_play_line "sleep_trooper02")
	(performance_play_line "sleep_trooper03")
	(performance_play_line "sleep_trooper04")
	(performance_play_line "look_up_trooper01")
	(performance_play_line "look_up_trooper02")
	(performance_play_line "look_up_trooper03")
	(performance_play_line "look_up_trooper04")
	(cs_abort_on_damage (performance_get_actor trooper01) 1)
	(performance_play_line "abort_on_damage")
)

(script static void (thes_trooper_immediate_salute)
	(performance_play_line "salute_animation")
)

(script static void (thes_trooper_immediate_stagger_explosions)	(performance_play_line "sleep_trooper01")
	(performance_play_line "sleep_trooper02")
	(performance_play_line "sleep_trooper03")
	(performance_play_line "sleep_trooper04")
	(performance_play_line "stagger_trooper01")
	(performance_play_line "stagger_trooper02")
	(performance_play_line "stagger_trooper03")
	(performance_play_line "stagger_trooper04")
)

(script static void (thes_trooper_immediate_wave)
	(performance_play_line "wave_animation")
)

(script static void (thes_elite_wake_grunt)
	(performance_play_line "move_to_center")
	(performance_play_line "wake_grunt_animation")
)

(script static void (thes_grunt_warm_fire)
	(performance_play_line "move_to_center")
	(performance_play_line "warm_fire_animation")
)

(script static void (thes_brute_celebrate)
	(performance_play_line "move_to_center")
	(performance_play_line "celebrate_animation")
)

(script static void (thes_skirmisher_marine_desecration)
	(performance_play_line "move_to_center")
	(performance_play_line "marine_desecration_animation")
)

(script static void (thes_civilian_injured)
	(performance_play_line "play_anim_chest")
	(performance_play_line "play_anim_gut1")
	(performance_play_line "play_anim_gut2")
	(performance_play_line "play_anim_leg1")
	(performance_play_line "block")
)

(script static void (thes_female_injured)
	(performance_play_line "anim_play_chest")
	(performance_play_line "anim_play_gut1")
	(performance_play_line "anim_play_gut2")
	(performance_play_line "anim_play_leg")
	(performance_play_line "block")
)

